### ISSUE TITLE
caddy-git 1.0.1

### ISSUE THREAD

**Issue by greenpau** [greenpau/caddy-git#1]
Inspired by [$100](https://github.com/vrongmeal/caddygit/pull/5#issuecomment-1010440830).

**Comment by greenpau** [comment]
Released https://github.com/greenpau/caddy-git/releases/tag/v1.0.1

**Comment by joeworkman** [comment]
I am about to play with this now. Thank you for taking the time for this.

I do think that in order to properly support webhooks, it would be important to secure the request with the secret key. https://docs.github.com/en/developers/webhooks-and-events/webhooks/securing-your-webhooks

It would be nice to also be able to run a command after the repo is pulled down. However, I think this could be accomplished with a git hook as well. 🤔

Lastly what about private repositories? Would I need to create ssh keys for the caddy user so that it has auth to that repo? Got any other ideas?

**Comment by greenpau** [comment]
> I am about to play with this now. Thank you for taking the time for this.

@joeworkman , there is still https://github.com/greenpau/caddy-git/issues/2#issuecomment-1011323517 to be solved in the upstream repo.

> I do think that in order to properly support webhooks, it would be important to secure the request with the secret key. https://docs.github.com/en/developers/webhooks-and-events/webhooks/securing-your-webhooks

You can secure an endpoint with `caddy-authorize` plugin. You can pass JWT token in `Authorization: Bearer`. Additionally, you can use `caddy-auth-portal` together with `caddy-authorize` to set up authentication with `X-API-Key` header.

I recently recorded a video about setting up local auth: https://www.youtube.com/watch?v=k8tbbffMGZk

> It would be nice to also be able to run a command after the repo is pulled down. However, I think this could be accomplished with a git hook as well. 🤔

Yes. Just open separate issues for the asks.

> Lastly what about private repositories? Would I need to create ssh keys for the caddy user so that it has auth to that repo? Got any other ideas?

Same as above. 

Generally, it is pretty basic.
1. Tell the Caddyfile directives you need, e.g.

```
git {
  repo foo {
    auth [password <username> <password> | ssh <path/to/key>]
  } 
}
```

2. Then, tell what you want to do with the directives.

This plugin is pretty trivial. If you know Go, then extending it is simple.

For example, the Caddyfile directives usually go to `caddyfile.go`:

https://github.com/greenpau/caddy-git/blob/10e5d772a3708d65d8fb28a200b16bc77c35019d/caddyfile.go#L95-L113

The properties associated with a repo (e.g. url, username, password, etc.) go to `pkg/service/config.go`:

https://github.com/greenpau/caddy-git/blob/10e5d772a3708d65d8fb28a200b16bc77c35019d/pkg/service/config.go#L28-L38

The key is asking questions and then "sky is the limit."

**Comment by joeworkman** [comment]
Thank you. I am an extreme n00b with both Go and Caddy. So bare with me. So this plugin is currently reliant on #2 getting resolved in go-git. 

If you don't mind, I will try to mockup what my Caddyfile would look like once it's all resolved. I will review your video and other docs to see if I can get is as close as we can to ideal.

**Comment by greenpau** [comment]
>  I am an extreme n00b with both Go and Caddy. So bare with me.

@joeworkman, 👍

The plugin works. The initial `git clone` works, but the `git pull` on webhook does not (because of the upstream).
 
> If you don't mind, I will try to mockup what my Caddyfile would look like once it's all resolved

Exactly, focus on creating Caddyfile configs that do not fail 😄 Then, it is just about enabling/requesting features.

**Comment by joeworkman** [comment]
Here is an example Caddyfile that I have setup so far... 

```
www.aspecthq.com {
    git {
        repo aspecthq.com {
            base_dir /var/www/aspecthq.com
            url https://gitlab.com/joeworkman/aspecthq.com.git
            branch master
            depth 1
            auth ssh /var/www/ssh/id_rsa.pub
        }
    }
    log {
        output file /var/log/caddy/aspecthq.com/access.log {
            roll_size 3MiB
            roll_keep 5
            roll_keep_for 48h
        }
    }
    handle_errors {
        respond "{http.error.status_code} {http.error.status_text}"
    }
    route /update {
        method POST
        git update repo aspecthq.com
    }
    encode gzip zstd
    php_fastcgi unix//run/php/php8.1-fpm.sock
    file_server
    root * /var/www/aspecthq.com
    push
  }
}
```

**Comment by greenpau** [comment]
@joeworkman on mobile. will explain later why.

change to:

git {
        repo aspecthq.com {
            base_dir /var/www/aspecthq.com
            url https://gitlab.com/joeworkman/aspecthq.com.git
            branch master
            depth 1
            auth ssh /var/www/ssh/id_rsa.pub
        }
    }

www.aspecthq.com {
   
    log {
        output file /var/log/caddy/aspecthq.com/access.log {
            roll_size 3MiB
            roll_keep 5
            roll_keep_for 48h
        }
    }
    handle_errors {
        respond "{http.error.status_code} {http.error.status_text}"
    }
    route /update {
        method POST
        git update repo aspecthq.com
    }
    encode gzip zstd
    php_fastcgi unix//run/php/php8.1-fpm.sock
    file_server
    root * /var/www/aspecthq.com
    push
  }
}

**Comment by greenpau** [comment]
> I have been watching your video and finding it hard to see the correlation with the webhook secret key. The webhook secret key is pretty simple. It's purely making sure that a specific header has a specific value.
 
@joeworkman , you are correct. This is just a feature to add.

**Comment by greenpau** [comment]
@joeworkman , I added the feature requests to the issues and fixed the git pull issue. You should be good to go.

**Comment by greenpau** [comment]
@joeworkman , you should be good to go with [v1.0.3](https://github.com/greenpau/caddy-git/releases/tag/v1.0.3). It now supports webhooks and authentication. Please see configuration examples: https://github.com/greenpau/caddy-git#getting-started

**Comment by joeworkman** [comment]
I got everything mostly working! It's 1am thoughI am sure that I will get it done tomorrow.

**Comment by joeworkman** [comment]
Are you doing a straight `git pull`? Or is there a way to do `git pull --rebase`?

**Comment by greenpau** [comment]
> Are you doing a straight git pull? Or is there a way to do git pull --rebase?

Just git pull. Rebase might require editing, which isn’t quite possible with caddy.

here are the options: https://github.com/greenpau/caddy-git/blob/2731af4b333ba26078a7e0589bd962a809424d7c/pkg/service/repo.go#L196

additionally, you could see go-git options here:

https://github.com/go-git/go-git/blob/32c4f532abd57797322e97d95dfa02821980e309/options.go#L92

**Comment by joeworkman** [comment]
I have been trying to figure this out without bothering you. Here is my config. 

```
{
    git {
        repo aspecthq.com {
            base_dir /var/www
            url https://gitlab.com/joeworkman/aspecthq.com.git
            branch master
            depth 1
            # auth ssh /var/www/ssh/id_rsa.pub
            webhook name X-Gitlab-Token go-caddy-git-go
            # post pull exec {
            #     name Pager
            #     command /usr/local/bin/pager
            #     args "pulled authp.github.io repo"
            # }
        }
    }
}
aspecthq.com {
    redir https://www.aspecthq.com{uri}
}
www.aspecthq.com {
    log {
        output file /var/log/caddy/aspecthq.com/access.log {
            roll_size 3MiB
            roll_keep 5
            roll_keep_for 48h
        }
    }
    handle_errors {
        respond "{http.error.status_code} {http.error.status_text}"
        # rewrite * /{http.error.status_code}.html
        # file_server
    }
    route /update {
        git update repo aspecthq.com
    }
    encode gzip zstd
    php_fastcgi unix//run/php/php8.1-fpm.sock
    file_server
    root * /var/www/aspecthq.com
    push
}
```

I noticed that if I already have the folder created (`/var/www/aspecthq.com`), then the repo would not get initialized. I have to run the initial `git clone` myself. 

Whenever webhook gets executed, I am getting this error... 

```
Jan 14 15:57:47 nycaddy caddy[191566]: {"level":"warn","ts":1642193867.4170184,"logger":"http.handlers.git","msg":"failed updating repo","repo_name":"aspecthq.com","error":"reference has changed concurrently"}
```

Then only enough, when I run `git status` on the repo, I get this... 

```
On branch master
Your branch is based on 'origin/master', but the upstream is gone.
  (use "git branch --unset-upstream" to fixup)

nothing to commit, working tree clean
```

**Comment by joeworkman** [comment]
If I allow caddy-git to create the folder and clone the repo, I get a different error when the webhook is used. 

```
Jan 14 16:14:28 nycaddy caddy[192921]: {"level":"warn","ts":1642194868.222069,"logger":"http.handlers.git","msg":"failed updating repo","repo_name":"aspecthq.com","error":"object not found"}
```

If I run `git status` the output claims that it's up to date. However, there is one change that needs to be pulled down. 

```
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

**Comment by greenpau** [comment]
> If I allow caddy-git to create the folder and clone the repo, I get a different error when the webhook is used.

@joeworkman , if this is still an issue, please create a separate issue for this.
