### ISSUE TITLE
feature: git matcher routes

### ISSUE THREAD

**Issue by joeworkman** [greenpau/caddy-git#10]
> A clear and concise description of what you want the system to do.

It would be good to be able to define a matcher route instead of defining an explicit route. 

> What are the Caddyfile directives that need to be added.

Current:

```
route /update {
    git update repo aspecthq.com
}
```

Requested: 

```
git /update update repo aspecthq.com
```

**Comment by greenpau** [comment]
@joeworkman , please see "routeless" config example.

https://github.com/greenpau/caddy-git/blob/b15e3b50ffd2d164574a985079317d9f2390c330/assets/config/routeless/Caddyfile#L23-L28

FYI, will release this weekend.
