### ISSUE TITLE
feature: Secure GitHub webhooks

### ISSUE THREAD

**Issue by joeworkman** [greenpau/caddy-git#11]
> A clear and concise description of what you want the system to do.

The webhooks feature cannot  currently be used properly with Github. The reason for this is that the web hook header needs to be compared securely for each request. It's not as simple as just comparing the strings in the web hook header. 

Here are the docs for securing the web hooks for Github. https://docs.github.com/en/developers/webhooks-and-events/webhooks/securing-your-webhooks

**Comment by greenpau** [comment]
@joeworkman , please test it with latest https://github.com/greenpau/caddy-git/releases/tag/v1.0.5
