### ISSUE TITLE
feature: Polling of repo for changes at a given interval

### ISSUE THREAD

**Issue by djt** [greenpau/caddy-git#12]
> A clear and concise description of what you want the system to do.

Polling to allow for private deployments to check repository for changes to trigger a pull.

> What are the Caddyfile directives that need to be added.

Add Caddyfile directive:

```
git {
  repo foo {
    interval <seconds>
  }
}
```

I love the work you've done on this, I was quite disappointed when I found that references online to http.git were for caddy v1 so this really fills a void.  

For servers that have open access it works great, but some internal work I do does not allow external traffic (for the webhook to hit) which is why the polling would be super beneficial.

**Comment by greenpau** [comment]
> Polling to allow for private deployments to check repository for changes to trigger a pull.

@djt, did you check whether `update every <seconds>` does what you want? I don't remember whether I implemented it or not.

https://github.com/greenpau/caddy-git/blob/0401e3fc075afb70b4f618475864e07657502616/caddyfile.go#L48

**Comment by greenpau** [comment]
@djt , never mind ... I need to implement this.

**Comment by greenpau** [comment]
@djt , this is now part of `v1.0.6`

**Comment by djt** [comment]
Great, thanks so much Paul.

Such great work you're doing with this.

**Comment by djt** [comment]
@greenpau I've been using this and it works great, one little bug though that may be due to my own config.

I have the --watch flag run with caddy to update on config changes, and was recently testing out a new server config.  It looks like the timer from the prior config does not end when a new one is loaded.

A quick test will allow you to see, set "update every 1" in the config and then edit it to "update every 60", config will reload but the old timer will still run.  If you repeat this, even for an unrelated config change, multiple timers can be seen running.

Let me know if you need any further details, or if you'd rather me open a new issue.
