### ISSUE TITLE
feature: run command after pull 

### ISSUE THREAD

**Issue by joeworkman** [greenpau/caddy-git#3]
It could be convenient to be able to define a command that would be ran after the repository is pulled down.

**Comment by greenpau** [comment]
> It could be convenient to be able to define a command that would be ran after the repository is pulled down.

@joeworkman , what would be the example? 

```
git {
  repo <foo> {
    post pull cmd <args>
  }
}
```

**Comment by joeworkman** [comment]
I will have to default to your best practices with Caddy and Go on this one.

**Comment by greenpau** [comment]
@joeworkman , FYI, here is the syntax I have for this.

```
git {
  repo <foo> {
    post pull exec {
      name Pager
      command /usr/local/bin/pager
      args "pulled authp.github.io repo"
    }
  }
}
```

**Comment by greenpau** [comment]
@joeworkman , this feature is supported in [v1.0.4](https://github.com/greenpau/caddy-git/releases/tag/v1.0.4).

**Comment by greenpau** [comment]
@joeworkman , connect with me on LinkedIn and we can chat there. If you have time right now, I can get on the phone with you and help you through the setup.
