### ISSUE TITLE
feature: add support for webhooks

### ISSUE THREAD

**Issue by greenpau** [greenpau/caddy-git#5]
Per @joeworkman,

> webhook secret key is pretty simple. It's purely making sure that a specific header has a specific value.
> For Github the header is X-Hub-Signature-256. We simply need to compare that with the stored key.
> FYI. Gitlab's header for web hooks is X-Gitlab-Token

Add Caddyfile directive:

```
git {
  repo foo {
    webhook name <header> <secret>
  } 
}
```

When a request comes via API endpoint, inspect the header and authorize based on the presence of the webhook header and secret.

**Comment by QuLogic** [comment]
It doesn't appear that you actually [validate `X-Hub-Signtature-256`](https://docs.github.com/en/developers/webhooks-and-events/webhooks/securing-your-webhooks#validating-payloads-from-github)?

**Comment by greenpau** [comment]
@QuLogic , want to put a fix? :-)

**Comment by greenpau** [comment]
> It doesn't appear that you actually validate X-Hub-Signature-256

Reopening it.

**Comment by greenpau** [comment]
Will address the signature validation via https://github.com/greenpau/caddy-git/issues/11
